### ISSUE TITLE
When you have a custom weapon equipped and you touch a resupply cabinet, your active weapon is changed to the custom weapon.

### ISSUE THREAD

**Issue by martyTF** [CreatorsTF/gameservers#5] opened 2021-08-19 04:27 UTC

**Comment by zonical** [comment] 2021-08-19 04:45
This is _most likely_ due to tf_persist_item being disabled on a patch to fix MvM crashes if I remember correctly. I'll need to do more specific testing to see if this fixes it as I can't fully remember if it does.

**Comment by nosoop** [comment] 2021-08-21 07:14
Yes, this would be caused by other plugins re-equipping destroyed items (which is what the persist item plugin is intended to prevent).  A hotfix would be to force the correct slot on change via `Weapon_Switch`, but the timing depends on when C.TF econ applies its items.

**Comment by zonical** [comment] 2021-08-21 09:15
We're planning to re-enable `tf_persist_item` on our next major patch which isn't too far away. This should hopefully fix this issue and #6.

**Comment by sapphonie** [comment] 2021-09-10 20:05
Closed in a0f71bb208490e9019756b7810b83833726089d3

**Closed by sapphonie** 2021-09-10 20:05 UTC
Labels: bug
